// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfRjpXeC2-AIsb-Uqp3o25eRDwtFDrpfA',
    appId: '1:197502606340:web:795e621c57e5bf55d06951',
    messagingSenderId: '197502606340',
    projectId: 'bustrack-11a2a',
    authDomain: 'bustrack-11a2a.firebaseapp.com',
    storageBucket: 'bustrack-11a2a.appspot.com',
    measurementId: 'G-30C1035KVJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb3XbMtkEhFo_U5FKX0bZlSVhLIzcvF3k',
    appId: '1:197502606340:android:52f0d97ae6940f6dd06951',
    messagingSenderId: '197502606340',
    projectId: 'bustrack-11a2a',
    storageBucket: 'bustrack-11a2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhiplOtJWiJ97SMgG0wMw8MqqQhjtGe4g',
    appId: '1:197502606340:ios:d8116e973dfbf5e8d06951',
    messagingSenderId: '197502606340',
    projectId: 'bustrack-11a2a',
    storageBucket: 'bustrack-11a2a.appspot.com',
    iosBundleId: 'com.example.busTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhiplOtJWiJ97SMgG0wMw8MqqQhjtGe4g',
    appId: '1:197502606340:ios:e908c37d0131f842d06951',
    messagingSenderId: '197502606340',
    projectId: 'bustrack-11a2a',
    storageBucket: 'bustrack-11a2a.appspot.com',
    iosBundleId: 'com.example.busTrack.RunnerTests',
  );
}
